# Generated by Django 5.2.1 on 2025-05-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='post',
            name='photo2',
            field=models.ImageField(default='photo', upload_to='photo'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo3',
            field=models.ImageField(default='photo', upload_to='photo'),
        ),
    ]
